name: navigation
description: "Modular, type-safe navigation framework for Flutter."
version: 1.1.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      ref: linter-v1.0.2
