name: app_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  api_network:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: infrastructure/network/api_network
      ref: api_network-v1.2.0
  dependencies:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: shared/dependencies
      ref: dependencies-v1.2.0
  di:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: shared/di
      ref: di-v1.1.0
  dio_network:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: infrastructure/network/dio_network
      ref: dio_network-v1.3.0
  failures:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: core/failures
      ref: failures-v2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  injectable_generator: any
  retrofit_generator: any
  json_serializable: any

flutter:
  uses-material-design: true