name: app_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  api_network:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/network/api_network
      ref: api_network-v1.2.3
  dependencies:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: shared/dependencies
      ref: dependencies-v1.3.0
  di:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: shared/di
      ref: di-v1.1.2
  dio_network:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/network/dio_network
      ref: dio_network-v1.3.3
  failures:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: core/failures
      ref: failures-v2.0.2
  navigation:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: fondation/navigation
      ref: navigation-v1.1.1
  go_router: ^17.3.0
  state_management:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: fondation/state_management
      ref: state_management-v2.1.2
  api_storage:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/storage/api_storage
      ref: api_storage-v1.1.0
  hive_storage:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/storage/hive_storage
      ref: hive_storage-v1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  injectable_generator: any
  memory_storage:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/storage/memory_storage
      ref: memory_storage-v1.1.1
  retrofit_generator: any
  json_serializable: any

flutter:
  uses-material-design: true