name: failures
description: "A package that contains all the failure classes used in the project. This package is designed to be a centralized location for defining and managing failure types, making it easier to handle errors and exceptions throughout the application. By using this package, developers can ensure consistency in error handling and improve the maintainability of the codebase."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      ref: linter-v1.0.1