name: dependencies
description: "A shared package for managing dependencies across the project."
version: 1.1.0

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.2
  equatable: ^2.0.8
  json_annotation: ^4.11.0
  retrofit: ^4.9.2