name: dio_network
description: "Network module for handling API calls and network-related operations."
version: 1.2.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  api_network:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: infrastructure/network/api_network
      ref: api_network-v1.0.0
  dependencies:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: shared/dependencies
      ref: dependencies-v1.2.0
  failures:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: core/failures
      ref: failures-v1.1.0
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      ref: linter-v1.0.1