name: dio_network
description: "Network module for handling API calls and network-related operations."
version: 1.2.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  dependencies:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: shared/dependencies
      ref: dependencies-v1.1.0
  failures:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: core/failures
      ref: failures-v1.1.0
  flutter:
    sdk: flutter
  response:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      path: core/response
      ref: response-v1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter:
    git:
      url: https://github.com/arkariz/advance-mobile-platform
      ref: linter-v1.0.1