name: models
description: "A Flutter package for core models."
version: 1.1.2
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  dependencies:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      path: shared/dependencies
      ref: dependencies-v1.3.0

dev_dependencies:
  linter:
    git:
      url: git@gitlab.bankcapital.co.id:mobile-services/mobile-platform.git
      ref: linter-v1.0.2
  test: any